# Generated by Django 5.2.16 on 2026-07-17 14:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_person', models.CharField(max_length=200)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('project_type', models.CharField(choices=[('building', 'Building Construction'), ('road', 'Road Construction'), ('water', 'Water Supply'), ('sanitation', 'Sanitation'), ('renovation', 'Renovation'), ('engineering', 'Civil Engineering'), ('equipment', 'Equipment Rental'), ('other', 'Other')], max_length=30)),
                ('project_location', models.CharField(max_length=250)),
                ('estimated_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('expected_start_date', models.DateField(blank=True, null=True)),
                ('project_description', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='quotes/attachments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png'])])),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Reviewing'), ('contacted', 'Contacted'), ('quoted', 'Quote Sent'), ('approved', 'Approved'), ('declined', 'Declined'), ('closed', 'Closed')], default='new', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
